version: '3.8'

services:
  auth_api:
    container_name: auth_api
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=auth_users
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=users
    volumes:
      - .:/usr/src/app
    depends_on:
      - auth_users
    networks:
      - backend_network

  auth_users:
    container_name: auth_users
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - backend_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - PMA_HOST=auth_users
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - auth_users
    networks:
      - backend_network

volumes:
  mysql_data:

networks:
  backend_network:
    driver: bridge
